services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "LATEST"
      MEMORY: "12G"
      MAX_PLAYERS: "4"
      ENABLE_COMMAND_BLOCK: "false"
      DIFFICULTY: "hard"
      MODE: "survival"
      LEVEL_NAME: "Hergetron's Server"
      VIEW_DISTANCE: "32"
      ONLINE_MODE: "true"
      PVP: "true"
    volumes:
      - ./data:/data
